apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
data:
  APP_HOST: {{ .Values.config.appHost | quote }}
  APP_PORT: {{ .Values.config.appPort | quote }}
  PUBLIC_BASE_URL: {{ printf "https://%s" .Values.ingress.host | quote }}
  DEBUG: {{ .Values.config.debug | quote }}
  ENVIRONMENT: {{ .Values.config.environment | quote }}
  MAX_CONCURRENT_TRANSCRIPTIONS: {{ .Values.config.max_concurrent_transcriptions | quote }}
  JWT_ALGORITHM: {{ .Values.config.jwtAlgorithm | quote }}
  JWT_EXPIRATION_MINUTES: {{ .Values.config.jwtExpirationMinutes | quote }}
  POSTGRESQL_HOST: {{ .Values.database.host | quote }}
  POSTGRESQL_PORT: {{ .Values.database.port | quote }}
  POSTGRESQL_DB_NAME: {{ .Values.database.name | quote }}
  OTEL_ENDPOINT: {{ .Values.config.otelEndpoint | quote }}
  CRW_BASE: {{ .Values.config.crwBase | quote }}
  LLM_BASE_URL: {{ .Values.config.llmBaseUrl | quote }}
  LLM_MODEL: {{ .Values.config.llmModel | quote }}
  LLM_API_KEY: {{ .Values.config.llmApiKey | quote }}
  VALKE_SERVICE_URL: {{ .Values.config.valkeyServiceUrl | quote }}
  VALKEY_SERVICE_PORT: {{ .Values.config.valkeyServicePort | quote }}
  GARAGE_ENDPOINT: {{ .Values.config.garageEndpoint | quote }}
  GARAGE_ACCESS_KEY: {{ .Values.config.garageAccessKey | quote }}
  GARAGE_SECRET_KEY: {{ .Values.config.garageSecretKey | quote }}
